### ISSUE TITLE
MCP1 (old Boeing style) not supported? A32NX_DispA32NX_AP_MCP1 is not known

### ISSUE THREAD

**Issue by joeherwig** [joeherwig/A32nx-LINDA-aircraft-module#44] opened 2022-01-12 21:51 UTC
FSUIPC7.log throws error:

`LUA Error: C:\FSUIPC7\linda/aircrafts/FBW A320/actions.lua:2171: attempt to call global 'A32NX_DispA32NX_AP_MCP1' (a nil value)`
See: https://github.com/joeherwig/A32nx-LINDA-aircraft-module/blob/main/A32nx/LINDA/aircrafts/FBW%20A320/actions.lua#L2171

The called function seems not to exist. So currently no MCP1 supported.

**Comment by scotflieger** [comment] 2022-01-12 22:22
This is a corruption of the function name resulting from a global replace. Not all MCP1 display functions were copied across in the conversion. Further investigation required.

**Comment by scotflieger** [comment] 2022-01-12 22:23
Should be marked as a Bug.

**Comment by joeherwig** [comment] 2022-01-12 22:27
Marked as bug. :-)

**Comment by joeherwig** [comment] 2022-01-18 21:47
function A32NX_DispA32NX_AP_MCP1 
function A32NX_DispGear_MCP1 
function A32NX_DispFlaps_MCP1

all not existing underneath my FSUIPC7 folder.
So clear why it can't work.

**Comment by scotflieger** [comment] 2022-01-18 22:05
These functions originally had the AB_ prefix when I copied them from the Aerosoft A3XX module. I will look at these shortly. The problem is that I don't own a MCP1(original) - only the MCP2(Boeing) and MCP2a(Airbus) for testing purposes.

**Closed as completed** 2022-02-09 11:57 UTC
Labels: bug
